### ISSUE TITLE
Papercuts priorization before we consider v2

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1009]
> **UPDATE Apr '22**: We are not looking for external contributions to address these.

Original: #857. Locked to ensure we don't lose focus a second time.

List of papercuts we're currently prioritizing based on their impact. Once these are completed, we will start drafting what v2 looks like as we aim towards modularization.

> NOTE: Any item missing link means we must create an issue yet. This is in anticipation of moving the central roadmap back to each respective repository - just haven't had the bandwidth to do any of that.

## High impact

- [ ] [**Code quality**: Integ test with external dependencies](https://github.com/awslabs/aws-lambda-powertools-python/issues/1251) #1226
- [ ] [**Docs**: Move code snippets into dedicated python files so they can be linted/formatted then embedded in the docs. It makes highlighting slightly harder but we can achieve consistency and prevent mistakes we keep on making](https://github.com/awslabs/aws-lambda-powertools-python/issues/1364). See #1004, #1061 -- @heitorlessa 
- [ ] **Idempotency**: [Remove data record lock in case of timeout](https://github.com/awslabs/aws-lambda-powertools-python/issues/1038) -- @rubenfonseca 

## Low impact

- [ ] [**Logger**: Provide autocomplete custom date formats (ISO8601) for `datefmt` field](https://github.com/awslabs/aws-lambda-powertools-python/issues/946)
- [ ] [**Tracer**: Typing SubSegment and Context Manager](https://github.com/awslabs/aws-lambda-powertools-python/issues/1375)
- [ ] [**Batch**: Improve maintainability of batch processing functional tests](https://github.com/awslabs/aws-lambda-powertools-python/issues/1363)
- [ ] [**Idempotency**: Consider refactoring test setup, potentially DynamoDB Local for functional](https://github.com/awslabs/aws-lambda-powertools-python/issues/1360) (not integration)
- [ ] [**Contributions**: Pre-configure GitPod and update Contributing guidelines](https://github.com/awslabs/aws-lambda-powertools-python/issues/1361) (Poetry didn't work previously; it works now)

## Maintenance automation

- [ ] [**Actions**: React to labels `size/XL`, `size/XXL` by adding `triage` label for maintainers attention, and suggest breaking the PR to reduce the chances of bugs being introduced due to cognitive load](https://github.com/awslabs/aws-lambda-powertools-python/issues/1331)
- [ ] [**PR verbatim enforcement**: Ensure CI fails if PR content doesn't have required acknowledgements](https://github.com/awslabs/aws-lambda-powertools-python/issues/1334)
- [ ] [**Actions**: Add conditional to catch for a potential future`null` on release workflow](https://github.com/awslabs/aws-lambda-powertools-python/issues/1362). Idea: have an automated mechanism to ensure +1 person reviewed release notes and version

## Completed

- [x] [**Docs:** API Gateway sample layout](https://github.com/awslabs/aws-lambda-powertools-python/issues/835)
- [x] [**Parser:** Typing on model subclassing](https://github.com/awslabs/aws-lambda-powertools-python/issues/849)
- [x] [**Parser:** Typing when using envelope](https://github.com/awslabs/aws-lambda-powertools-python/issues/802)
- [x] [**Event Handler:** BaseProxyEvent missing overload to match Proxy Type Request Context](https://github.com/awslabs/aws-lambda-powertools-python/issues/761)
- [x] [**Tracer:** Typing provider when none is passed](https://github.com/awslabs/aws-lambda-powertools-python/pull/861)
- [x] [**Metrics:** Typing SingleMetric context manager](https://github.com/awslabs/aws-lambda-powertools-python/issues/857)
- [x] [**Tracer:** Add method to ignore certain hostname/URLs to be traced](https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/35)
- [x] [**Docs:** Update public Slack invite with new link as the previous one expired](https://github.com/awslabs/aws-lambda-powertools-python/commit/8cfa7737139286a061979eec0c1a4c12e720a107)
- [x] [**Event Handler:** Do not throw exception if `json_body` doesn't have JSON but return `None`](https://github.com/awslabs/aws-lambda-powertools-python/issues/881)
- [x] [**MyPy:** Address all MyPy errors and enable MyPy at CI level](https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/3)
- [x] [**Legacy Batch:** Delete > 10 messages async](https://github.com/awslabs/aws-lambda-powertools-python/pull/818)
- [x] **Layers**: Migrate internal CI/CD pipeline dedicated to Lambda Layers to AWS Code*. This will operational effort in maintaining two release processes, and allow us to add additional AWS regions - @am29d  owning it
- [x] **Project Management**: Migrate [Powertools Roadmap](https://github.com/awslabs/aws-lambda-powertools-roadmap) tasks back to this repository with the new GitHub Projects Beta. This will best represent items we're currently prioritizing, plus automation - @heitorlessa owning it
- [x] **Project Management**: Refresh our Contributing guide with GitPod.io, more details on what circumstances a PR can be closed/reopened, and expand what behaviors we will not tolerate beyond the general code of conduct - @heitorlessa owning it
- [x] **Logger**: Lambda Context and state not being explicitly cleared when bringing custom formatters #1042
- [x] **End-to-end tests mechanics**:  Create RFC for mechanism to run e2e tests on merge - @mploski owning it
    - This will give us confidence to remove `boto3` (>90% of package size) for Lambda Layers/SAR App
- [x] **Tests**: Experiment with pytest-benchmark and flaky plugin to retry performance tests that fail due to GitHub Actions CI shared hardware being overutilized at times
- [x] **PR linkage**: Link PRs to related issue, add `status/staged-next-release` label upon merge - linked PRs will close issues, need to have a second thought on whether this is okay
- [x] **Changelog append**: As PR titles are now consistently good, we need to revisit how [Git-chlog](https://github.com/git-chglog/git-chglog) might be modified to append to the existing changelog upon PR merge
- [x] **Review release process**: As mechanisms have been stable, it's time we revisit whether we can automate some manual steps without losing the human communication aspect of a release
- [x] **Code quality**: End-to-end test #1226
- [x] **Docs:** Change `Testing your code` docs section to reflect how customers would have to test their code (Batch and Event Handler being good examples to follow) - @cakepietoast owning it
- [x] **Actions**: Lockdown untrusted/3rd party GH Actions to use immutable git sha
- [x] **Parser**: Defensively pop dict keys in case event has been tampered. https://github.com/awslabs/aws-lambda-powertools-python/discussions/1228

**Comment by heitorlessa** [comment]
Closing in favour of individual issues now created using the new Maintenance template.
