### ISSUE TITLE
ci: PULL_REQUEST_TEMPLATE.md checklist wording

### ISSUE THREAD

**Issue by sliedig** [awslabs/aws-lambda-powertools-python#1314]
### What were you searching in the docs?

[PULL_REQUEST_TEMPLATE](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/PULL_REQUEST_TEMPLATE.md)

### How can we improve?

```markdown
Fix wording in checklist
```

## Checklist

Please leave checklist items unchecked if they do not apply to your change.

* [ ] [Meets tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.
