### ISSUE TITLE
Checklist before GA

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#33]
**UPDATE**: `Metrics.add_namespace` and `POWERTOOLS_METRICS_NAMESPACE` will be removed during GA.

Creating a checklist of activities to remember after finishing docs website

* [x] [Set coverage bar](https://github.com/awslabs/aws-lambda-powertools-python/pull/79)
* [x] [Clean up tests with GIVEN/WHEN/THEN](https://github.com/awslabs/aws-lambda-powertools-python/pull/79)
* [x] [Contributing guide](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/CONTRIBUTING.md)
* [x] Enable automation for repo management
    - [x] [Semantic pull requests](https://github.com/zeke/semantic-pull-requests)
    - [x] [Release drafter](https://github.com/release-drafter/release-drafter)
    - [x] [Workflow to publish to PyPi on release published](https://github.com/awslabs/aws-lambda-powertools-python/pull/58)
    - [x] [Stale issues](https://probot.github.io/apps/stale/)
    - [x] [Codecov](https://github.com/awslabs/aws-lambda-powertools-python/pull/59)
    - [x] [LGTM](https://lgtm.com/projects/g/awslabs/aws-lambda-powertools-python/)
    - [x] [pre-commit](https://github.com/awslabs/aws-lambda-powertools-python/pull/64)
* [x] Align `Metrics` API with the core utilities (e.g. service param)
* [x] Include security and complexity in CI flow
* [x] GitHub Issue templates
    - [x] [Pull Request, including checklists](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/PULL_REQUEST_TEMPLATE.md)
    - [x] [RFC](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/ISSUE_TEMPLATE/rfc.md)
    - [x] [Feature request](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md)
    - [x] [Bug report](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)
* [x] Label PRs, and cut 1.0.0 release notes
* [ ] ~~Main docs website to live under `/<runtime>`~~
* [x] Confirm whether `pytest` has now support for `pyproject.toml`
* [x] Add disclaimer that only Lambda official runtimes will be supported
* [x] Add note of appreciation for main contributors in GA PR
* [x] Investigate [CI Build Wheel for GitHub Actions](https://pypi.org/project/cibuildwheel/)
* [x] Experiment with Probot, semantic release bot, dependabot config
* [x] Rename repo to `aws-lambda-powertools-python`
* [x] Convert CHANGELOG to use KeepAChangeLog semantics
* [x] Build docs in develop, and both docs in master
* [x] Dependabot diffs for version bump
* [x] Fix WACG code text contrast issues

**Note** - Checklist updated ~~We might need to break into multiple repos as most tools are language specific, docs layout are vastly different, and dependabot can't seem to get multiple CHANGELOGs~~

**Comment by michaelbrewer** [comment]
@heitorlessa i was about to mention that the CHANGELOG.md file was not conforming to [Keep a Changelog format](https://keepachangelog.com/en/0.3.0/). Which is probably why depedabot is not probably picking up the diff between releases. But i see you have it on your TODO list :)

**Comment by heitorlessa** [comment]
I’m kinda puzzled it’s not picking up - I initially thought it wasn’t
picking up because we had CHANGELOG in a subfolder.

I’ll have to setup a dummy project, a dummy package, and probably look into
dependabot code to understand how they fetch them.

I’ll create an issue to investigate that :)

**Comment by michaelbrewer** [comment]
@heitorlessa to be clear. It is picking up the changelog file. It is just not selecting the diff, because the sections in the changelog does not have anchors on the release names. So it shows the whole file. 

So by updating the format to be more of a “standard” it should do both.

**Comment by heitorlessa** [comment]
Ah! Thanks for clarifying - I've just merged a PR from Tom that converts
our CHANGELOG to Keep a Changelog format

**Comment by michaelbrewer** [comment]
There are some great tools from conventional commit site that can generate this from you git commits and git tags. So you don’t have to had craft it.

**Comment by heitorlessa** [comment]
Yep - I checked them out. I’ll opt to partially generate the release notes,
but handcraft it as I didn’t like any generated Changelog I’ve seen out
there - It didn’t feel like it was for humans

**Comment by michaelbrewer** [comment]
@heitorlessa  - CHANGELOG.md diffs are now 100% working with dependabot.

**Comment by heitorlessa** [comment]
@cakepietoast updated GA description to add a note that `Metrics` method on adding a namespace and its env var will change before we go GA.
