### ISSUE TITLE
Papercuts we're currently prioritizing

### ISSUE THREAD

**Issue by whardier** [awslabs/aws-lambda-powertools-python#857]
Need to add proper ContextManager typing via typing.ContrxtManager in several places.

Currently overriding single_metric (-> ContextManager[SingleMetric]) and noticed several other areas where this needs done as well.

Also be nice if there was a proper DummySubSegment type returned for tracing provider.in_subsegment to avoid including types from aws modules to cast.

## Expected Behavior
Have rich type annotations along for the ride when using context managers.

## Current Behavior
Need to self annotate.

## Possible Solution
Add in proper type annotation to some or all of the context manager decorated functions.

**Comment by heitorlessa** [comment]
Thanks a lot for raising this @whardier ! I was about to create a list of papercuts we'd like to address, these being two of them.

The SubSegment typing is the most elaborate one, I need one full day to create and refactor a few things, including having an easy way to unit test your application with a Fake Tracer Provider.

**Comment by heitorlessa** [comment]
When you have a moment, could you help us by enumerating some of them like the SingleMetric ctx manager?

I'm gonna rename this to top papercuts so we can tackle them accordingly as many as possible 

![image](https://user-images.githubusercontent.com/3340292/144075378-1ae6f0f4-2425-42a0-85a3-95ded0342892.png)

**Comment by heitorlessa** [comment]
Top papercuts we'd like to address:

- [ ] [Docs: API Gateway sample layout](https://github.com/awslabs/aws-lambda-powertools-python/issues/835)
- [ ] [Parser: Typing on model subclassing](https://github.com/awslabs/aws-lambda-powertools-python/issues/849)
- [ ] [Parser: Typing when using envelope](https://github.com/awslabs/aws-lambda-powertools-python/issues/802)
- [ ] [Event Handler: BaseProxyEvent missing overload to match Proxy Type Request Context](https://github.com/awslabs/aws-lambda-powertools-python/issues/761)
- [x] [Tracer: Typing provider when none is passed](https://github.com/awslabs/aws-lambda-powertools-python/pull/861)
- [ ] Tracer: Typing SubSegment and Context Manager
- [ ] [Metrics: Typing SingleMetric context manager](https://github.com/awslabs/aws-lambda-powertools-python/issues/857)

**Comment by elliottyates** [comment]
A thought: it took me a few moments and tries to get unit testing working for some features (e.g. https://github.com/awslabs/aws-lambda-powertools-python/issues/706). One suggestion might be a dedicated area of the docs for unit testing, instead of hunting down the solutions for each feature.

**Comment by michaelbrewer** [comment]
Another one :) 
- [ ] https://github.com/awslabs/aws-lambda-powertools-python/pull/862

**Comment by michaelbrewer** [comment]
Docs PR:
- [ ] https://github.com/awslabs/aws-lambda-powertools-python/pull/864

**Comment by whardier** [comment]
single_metric PR:

* [ ] #865

**Comment by heitorlessa** [comment]
> Need to create an issue for it

Another one: Idempotency doesn't support serialization of data classes - both input (idempotency key) and return... it could be easily solved by inspecting if it's a dataclass, then using `asdict()`. `asdict()` is infamous for having a performance hit on deeply nested dataclasses, so we'll need to mention in the docs.

**Comment by heitorlessa** [comment]
- [ ] Internal papercut: Improve maintainability of batch processing functional tests (it should be easier to create tests)

**Comment by michaelbrewer** [comment]
We could already fixes, but definitely fits into this theme:

- [x] https://github.com/awslabs/aws-lambda-powertools-python/pull/869

**Comment by michaelbrewer** [comment]
> Another one: Idempotency doesn't support serialization of data classes - both input (idempotency key) and return... it could be easily solved by inspecting if it's a dataclass, then using asdict(). asdict() is infamous for having a performance hit on deeply nested dataclasses, so we'll need to mention in the docs.

@heitorlessa see https://github.com/awslabs/aws-lambda-powertools-python/pull/908

**Comment by michaelbrewer** [comment]
@heitorlessa - these 2 are ready to be reviewed and merged

- https://github.com/awslabs/aws-lambda-powertools-python/pull/910
- https://github.com/awslabs/aws-lambda-powertools-python/pull/908

**Comment by michaelbrewer** [comment]
Sorry @heitorlessa  a papercut fix caused another paper cut :P 

- [ ] - https://github.com/awslabs/aws-lambda-powertools-python/pull/926

**Comment by michaelbrewer** [comment]
Some typos and code clean up for data classes:

- [ ] - https://github.com/awslabs/aws-lambda-powertools-python/pull/937

**Comment by heitorlessa** [comment]
I'm locking this issue and will split them up into individual issues. We've accidentally got sidetracked in not tackling the actual top papercuts and started addressing new ones.
